### ISSUE TITLE
Plin for test simulations

### ISSUE THREAD

**Issue by lauracabayol** [igmhub/ForestFlow#1]
@jchavesmontero - I think we should consider a better approach for the following: 

Since data/mpg_xxx_plin.npz files are large, we are not storing them in the git directory. While for the training data 
one only needs to recompute them once and store them locally: 

Archive3D = GadgetArchive3D(
    base_folder=path_program[:-1], 
    folder_data=folder_lya_data, 
    force_recompute_plin=False,
    average='both'
)

this is not the case for the test simulations, where we need to do sometihng like: 

Archive3D.testing_data = Archive3D.get_testing_data(
    "mpg_central", force_recompute_plin=True
)

But when doing this, if once later wants to test another simulation, laoding the archive again is required, since the .testing_data is overwritten. 

This can be confussing, I think we should find a better solution for this.

**Comment by andreufont** [comment]
What are these plin files, and why are they large? If they contain the linear power spectrum given the cosmo in the sims (from CAMB/CLASS), these should be very small files...

**Comment by jchavesmontero** [comment]
The solution for the testing simulations was a hack before making something better. Nevertheless, it is important to note that you only need to run those once per testing simulation. I have no time at all now, but I will take a look at this after the meeting

**Comment by lauracabayol** [comment]
Yes, I know you only need to run this once. For us I don't think this would be a problem, but I think it can be problematic for other users and can lead to confussions. 

And sure! No rush! After the meeting. I opened the issue now to not forget about it

**Comment by jchavesmontero** [comment]
This issue has been fixed by the last commit
