### ISSUE TITLE
k1d_Mpc not set if return_p1d is False in emulator evaluator function

### ISSUE THREAD

**Issue by marlena6** [igmhub/ForestFlow#27]
P3DEmulator.evaluate has a line
`p1ds_pred = np.zeros(shape=(Nrealizations, len(k1d_Mpc)))`
that causes an error if `return_p1d` is False, as `k1d_Mpc` is only defined if True. Presumably this array should only be created if `return_p1d` is True.

**Comment by jchavesmontero** [comment]
I have just pushed a commit trying to fix this issue. I have to go to be now so I did not have time to validate it, let me know whether it works or not.

**Comment by marlena6** [comment]
It is working correctly now for all cases.
